name: the_movie_db
description: Mobile App for The Movie Data Base.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_multi_formatter: ^2.5.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  flutter_secure_storage: ^5.0.2
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.3

dev_dependencies:
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/posters/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # see https://flutter.dev/custom-fonts/#from-packages
